# Generated by Django 2.2.4 on 2019-08-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raitings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=300)),
                ('Value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Year', models.IntegerField(max_length=4)),
                ('Rated', models.CharField(max_length=300)),
                ('Released', models.CharField(max_length=300)),
                ('Runtime', models.CharField(max_length=300)),
                ('Genre', models.CharField(max_length=300)),
                ('Director', models.CharField(max_length=300)),
                ('Writer', models.CharField(max_length=300)),
                ('Actors', models.CharField(max_length=300)),
                ('Plot', models.CharField(max_length=300)),
                ('Language', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('Awards', models.CharField(max_length=300)),
                ('Poster', models.CharField(max_length=300)),
                ('Metascore', models.CharField(max_length=300)),
                ('imdbRating', models.IntegerField(max_length=300)),
                ('imdbVotes', models.IntegerField(max_length=300)),
                ('imdbID', models.CharField(max_length=300)),
                ('Type', models.CharField(max_length=300)),
                ('DVD', models.CharField(max_length=300)),
                ('BoxOffice', models.CharField(max_length=300)),
                ('Production', models.CharField(max_length=300)),
                ('Website', models.CharField(max_length=300)),
                ('Response', models.CharField(max_length=300)),
                ('Ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netapp.Raitings')),
            ],
        ),
    ]
