# Generated by Django 2.2.4 on 2019-08-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdbRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdbVotes',
            field=models.IntegerField(),
        ),
    ]
