# Generated by Django 2.2.4 on 2019-08-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netapp', '0003_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='Ratings',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='imdbRating',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='imdbVotes',
        ),
    ]
