# Generated by Django 2.2.4 on 2019-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp', '0004_auto_20190831_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
