# Generated by Django 2.2.4 on 2019-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp', '0006_auto_20190831_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdbRating',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdbVotes',
            field=models.CharField(max_length=300),
        ),
    ]
